### PR TITLE
Update faraday version in gemspec.

### PR DESCRIPTION
**Pull request by masayukioguni**

### CODE REVIEW

**Comment by ferhatsb** [comment]
So current one (pesimistic) can not use 0.9.x ?

**Comment by masayukioguni** [comment]
It worked without problems in the bundle install rather than bundle update.
This pull request will be closed.

**Comment by trantorLiu** [comment]
Would you update Faraday version to `~> 0.11.0`? I can't install the gem right now.

**Comment by hantuzun** [comment]
What is the error you get installing suggestgrid-ruby @trantorLiu?

**Comment by trantorLiu** [comment]
I have other gem using a newer version of Faraday, which conflicts to suggestgrid's spec.

```
Bundler could not find compatible versions for gem "faraday":
  In snapshot (Gemfile.lock):
    faraday (= 0.11.0)

  In Gemfile:
    google-cloud-translate was resolved to 1.0.1, which depends on
      google-cloud-core (~> 1.0) was resolved to 1.2.0, which depends on
        google-cloud-env (~> 1.0) was resolved to 1.0.1, which depends on
          faraday (~> 0.11)

    suggestgrid was resolved to 0.3.0, which depends on
      faraday (~> 0.10.0)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.

Bundler could not find compatible versions for gem "suggestgrid":
  In Gemfile:
    suggestgrid
```

**Comment by hantuzun** [comment]
Okay, we'll get you back in 12 hours.

**Pull request closed without merging**
